# Generated by Django 4.0.5 on 2022-06-09 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='liveUrl',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sourceUrl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
